### ISSUE TITLE
Use router-link in cellRendererFramework template

### ISSUE THREAD

**Issue by scleriot** [ag-grid/ag-grid-vue#1]
**I'm submitting a ...**
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to use a <router-link>component (from Vue Router library) in a cellRendererFramework, but I get the following error :

> Error when rendering component <router-link>: 
> TypeError: Cannot read property 'resolve' of undefined
> 

But when I try with another global declared component it works

**Minimal reproduction of the problem with instructions**
```html
<ag-grid-vue style="width: 100%; height: 400px;" class="ag-material" id="table" :columnDefs="table_columnDefs" :rowData="data" :gridOptions="gridOptions">
</ag-grid-vue>
```

```javascript
var Vue : require('vue');
var {AgGridVue} = require('ag-grid-vue');

Vue.component('ag-grid-vue', AgGridVue);

module.exports = {
   data() {
        return {
            gridOptions: {},
            table_columnDefs: [],
            data: []
        };
    },
   components: {
        'test-component': {
            template: '<router-link to="/test">Test</router-link>'
        }
    },
    mounted() {
		this.table_columnDefs = [
		            {
		                headerName: 'test',
		                cellRendererFramework: 'test-component'
		            }
		];
    }
}

```

**What is the motivation / use case for changing the behavior?**
Add a link when using Vue Router

**Please tell us about your environment:**
Compiling Vue with Browserify 

* **ag-grid-vue version:** 8.1.0

* **ag-Grid version:** 8.1.1

* **VueJS version:** 2.1.8

**Comment by lverre** [comment]
Hi,
Same issue... anyone worked this out?

**Comment by seanlandsman** [comment]
You need to provide a router to the component you're creating 

For example:

```
    import VueRouter from "vue-router";
    const router = new VueRouter();
```

```
        components: {
            'link-component': {
                router,
                template: '<router-link to="/master-detail">Test</router-link>'
            }
        }
```

You can either create a new router as above, or share the "root" router, but either way you need to make it available to the dynamically created components

**Comment by wordythebyrd** [comment]
@seanlandsman Did you test that?  I created a router instance and injected it with the router option on my component and this.$router is still undefined in the 'cellRendererFramework' component.

**Comment by ypolonsky** [comment]
@seanlandsman How can you "share" a root router?

I need a root router in order to use the name of the defined route, something like:
```
<template>
  <div>
    <router-link :to="{ name: 'Home', params: { id: '123456789', type: 'plain'}}">TEST</router-link>
  </div>
</template>
```
If I use a new router, like in your example, I'm getting error that "Home" is not found.

If I'm "sharing" the root router like this (using single file component):

```
<script>
import router from '../router/routes.js'
export default Vue.extend({
    router,
    name: 'LinkRenderer'
    }
  })
</script>
```
I'm getting the following error:

```
vue.esm.js?efeb:591 [Vue warn]: Error in render: "TypeError: Cannot read property 'resolve' of undefined"
found in
---> <RouterLink>
       <Root>
```
May be I cannot use a single file component with router-link as a renderer?

**Comment by brookpatten** [comment]
I'm having the same issue with using a single file component rather than an inline component.  Is there any way to provide the router instance to the grid without inlining the entire component?

**Comment by kennethchoe** [comment]
Here is how I resolved.

https://stackoverflow.com/questions/52121719/how-can-i-add-vue-router-link-as-ag-grid-vue-column/52211229#52211229

**Comment by seanlandsman** [comment]
@ypolonsky @brookpatten @kennethchoe 

This will work as expected in the next release - the router (ie this.$router) will be populated automatically for Vue components used within the grid.

thanks
