### ISSUE TITLE
Pass parameters to the component constructor before mounting it in vueComponentFactory.js

### ISSUE THREAD

**Issue by ajimenezml** [ag-grid/ag-grid-vue#17]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have not been able to use libraries like vue-i18n in components used in cell renderers since they need to be passed to the component constructor before mounting it

**Expected behavior**

A way to use libraries like vue-i18n in components used in cell renderers

**Minimal reproduction of the problem with instructions**

[![Edit ag-grid-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zn2z17x71m?module=%2Fsrc%2FComponent.vue)

**What is the motivation / use case for changing the behavior?**

There are many libraries that need to be initialized in this way

**Please tell us about your environment:**

* **ag-grid-vue version:** 16.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 16.0.1

* **VueJS version:** 2.5.13

* **Browser:** All

* **Language:** All

**Comment by wordythebyrd** [comment]
@ajimenezml, we had the same problem translating with vue-i18n within the ag-grid cell renderer.  As a workaround, we saved our instance of $t to our vuex store.  By doing this we were able to access $t via our store from within the component passed to the cell renderer.

**Comment by wordythebyrd** [comment]
Same issue with router-links in a cell rendered component.

**Comment by seanlandsman** [comment]
@ajimenezml @wordythebyrd Please update to 19x - it should work as expected now: https://codesandbox.io/s/5xrq14860n

@wordythebyrd The router links should also just work as expected now - take a look at https://github.com/seanlandsman/ag-grid-vue-routing
