### ISSUE TITLE
Filter vue components created and mounted twice.

### ISSUE THREAD

**Issue by Sevavietl** [ag-grid/ag-grid-vue#2]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Filter vue components created and mounted twice.

**Expected behavior**

Components should be created once.

**Minimal reproduction of the problem with instructions**

I have vuejs components filters. I need to set default filter values (that should be applied to filter data before user changes filter manually, and also this values should define the filter state when user opens filter manually). To do this I use API method to get a component. 
```
const filterComponent = this.api.getFilterInstance("orders_year").getFrameworkComponentInstance();
```
From the `mounted` hook I log to the console.

So I see log twice: when I get the component instance before hand to set default filter and when I open filter itself.

Is this expected behavior. If so, how can I set default filter values and keep the default values and filter values in sync?

Default filter model defined in `params.colDef.filterParams.defaultModel`. So I can get this data from component and provide it to `this.api.setFilterModel` method. Or I can use it to change filter component state and then call `this.params.filterChangedCallback();` from whitin.

Regardless of method filter component created twice.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-vue version:** 8.2.0

* **ag-Grid/ag-Grid-Enterprise version:** 8.2.0

* **VueJS version:** 2.0.1

* **Browser:** Chrome 56

* **Language:** ES6/7

**Comment by seanlandsman** [comment]
Hi

If you can provide a reproducible example of this I'm happy to take a look.

If you do I'll be happy to re open this issue

thanks
