### ISSUE TITLE
AgGridVue runtime error

### ISSUE THREAD

**Issue by lloydjatkinson** [ag-grid/ag-grid-vue#21]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Installing AgGrid/AgGridVue and following the documentation results in a Vue runtime error relating to the AgGridComponent.

**Expected behavior**
I would expect the grid component to work correctly as per the documentation.

**Minimal reproduction of the problem with instructions**

Please see the git repo I made to reproduce the problem.

https://github.com/lloydjatkinson/ag-grid-vue-runtime-error

`npm install -g @vue/cli`
`git clone https://github.com/lloydjatkinson/ag-grid-vue-runtime-error`
`cd ag-grid-vue-runtime-error`
`npm install`
`npm run serve`

![image](https://user-images.githubusercontent.com/5633938/39372643-d63ccdae-4a3c-11e8-8d3c-c3234aa8ebfd.png)

**What is the motivation / use case for changing the behavior?**
To enable Vue users to use AgGrid/AgGridVue.

**Please tell us about your environment:**
vue-cli, webpack, babel, Chrome
* **ag-grid-vue version:** 2.0.X

```
    "ag-grid": "^17.1.1",
    "ag-grid-vue": "^17.1.0",
    "vue": "^2.5.16"
```

* **Browser:** Chrome, Firefox, IE 11

* **Language:** ES6/7

**Comment by seanlandsman** [comment]
This will be resolved in our next release - current ETA is two weeks time
