### ISSUE TITLE
Vue Framework Components are Parentless

### ISSUE THREAD

**Issue by nmarshall23** [ag-grid/ag-grid-vue#22]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

I am trying to use Vue's [Provide / Inject](https://vuejs.org/v2/api/#provide-inject), to provide a function to a detail grid from the master. However I see that Framework Components created by ag Grid do not have their parent set.

From Vue's API Docs:
> Provide / Inject are used together to allow an ancestor component to serve as a dependency injector for all its descendants, regardless of how deep the component hierarchy is, as long as they are in the same parent chain.

**Current behavior**

My current workaround is to set the needed functions in gridOptions.context. That is added complexity to my components. I have to write components that only work with agGrid. 

* **ag-grid-vue version:** 17.1.1
* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
* **VueJS version:** 2.5.16
* **Language:** [ES2017]

**Comment by seanlandsman** [comment]
Hi,

This will work as expected in the next release - the parent (ie this.parent) will be populated automatically for Vue components used within the grid.

thanks
