### ISSUE TITLE
router-link is not working in CellRenderer of ag-grid in Vue JS application

### ISSUE THREAD

**Issue by ypolonsky** [ag-grid/ag-grid-vue#23]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I created the vue js applicaiton with two routes.  The first one opens the table with two columns. The second column has a celRenderer component which defined inline:

```
  import {AgGridVue} from 'ag-grid-vue'
  import VueRouter from 'vue-router'

  const router = new VueRouter();
...
      components: {
        'ag-grid-vue': AgGridVue,
        'link-renderer': {
          router,
          template: '<router-link to="/details">{{params.value}}</router-link>'
        }

```
The path "/details' is defined in the "root" router:
```
    routes: [
      { path: '/', name: 'grid',   component: Master },
      { path: '/details', name: 'entry', component: Details }
    ]
```
The second column definition includes custom cell renderer as defined above.
```
this.columnDefs = [
   { field: 'id', headerName: 'Row', width: 110 },
   { field: 'link', headerName: 'Link', width: 200, cellRendererFramework: 'link-renderer' }
]
```
When you open the master view and click the link in the second column cell, the browser shows the link "http://localhost:8086/#/details" in the browser's link (address) bar but does not show the details view defined in another single file vue component.

Note, that if I replace the cell renderer template with "hardcoded" tag, everything works as expected:
```
'link-renderer': {
  router,
  template: '<a href="#/details">{{params.value}}</a>'
}
```
I googled for similar issues and only found the closed issue https://github.com/ag-grid/ag-grid-vue-example/issues/3 which advises to use the approach I described.

I also tried to use this.$router instead of creating a new one.  This change gave me multiple errors stating that something cannot be resolved. 

I think, something is wrong how router is set up for the cell renderer component but don't know what to change.  I did not find any examples with router-link in a cell.  Is it an issue or I'm missing something in my code?

Thank you, I appreciate your help in resolving this issue.

**Expected behavior**

The expected behavior is to open the second "details" page in the browser window.

**Minimal reproduction of the problem with instructions**

I created a small project in github to illustrate the issue.  Please, get it from https://github.com/ypolonsky/vue-ag-grid-router-link-example
It runs in localhost:8086

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Mac OS X El Capitan
Intellij WebStorm
npm, simple webpack
All libraries are latest version you can get with npm install
* **ag-grid-vue version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **VueJS version:** 2.0.X  (2.9.3 on my computer)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I tried in Chrome and Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by kennethchoe** [comment]
I'm trying to solve the same problem here. Instead of defining another instance of `const router = new VueRouter();`, I wonder if you need to make the "root" Router available, as written in https://www.ag-grid.com/best-vuejs-data-grid/.

But when I did so by `import router from "@/router";`, I get an error:
```
vue.esm.js:591 [Vue warn]: Error in render: "TypeError: Cannot read property 'resolve' of undefined"

found in

---> <RouterLink>
       <Root>
```

**Comment by kennethchoe** [comment]
Here is how I resolved.

https://stackoverflow.com/questions/52121719/how-can-i-add-vue-router-link-as-ag-grid-vue-column/52211229#52211229

**Comment by seanlandsman** [comment]
Hi,

This will work as expected in the next release - the router (ie this.$router) will be populated automatically for Vue components used within the grid.

thanks
