### ISSUE TITLE
gridAutoHeight is not known as property of gridOptions

### ISSUE THREAD

**Issue by marjandejyab** [ag-grid/ag-grid-vue#25]
**I'm submitting a Bug** 

**Current behavior**
gridAutoHeight does not work. it raises "warning: invalid gridOptions property 'gridAutoHeight' did you mean any of these: headerHeight,rowHeight,groupHeaderHeight,getRowHeight,pivotHeaderHeight,pivotGroupHeaderHeight,detailRowHeight,floatingFiltersHeight"

**Expected behavior**
gridAutoHeight should be accepted as a property as mentioned in the documents

**Minimal reproduction of the problem with instructions**
1. Download the Example
2. Add gridAutoHeight: true to gridOptions
3. Run the project

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Webpack, VS-Code

* **ag-grid-vue version:** 
17.1.0

* **ag-Grid/ag-Grid-Enterprise version:** 
18.1.1

* **VueJS version:** 2.0.X
2.5.16

* **Browser:** 
Chrome 67

* **Language:** 
ES6

**Comment by thearabbit** [comment]
It work fine for me.
```js
<ag-grid-vue
      :column-defs="columnDefs"
      :row-data="rowData"
      :enable-col-resize="true"
      :grid-options="gridOptions"
      class="ag-theme-balham"
    >
    </ag-grid-vue>
---
data() {
    return {
      gridOptions: {
        gridAutoHeight: true,
      },
      columnDefs: null,
      rowData: null,
    }
  },
```

**Comment by marjandejyab** [comment]
hi @thearabbit 

I have just downloaded the latest version of sample and add gridAutoHeight property:
Sample Url: https://github.com/ag-grid/ag-grid-vue-example


```
beforeMount() {
            this.gridOptions = {};
            this.gridOptions.dateComponentFramework = DateComponent;

            this.gridOptions.gridAutoHeight = true; //Added to sample

            this.createRowData();
            this.createColumnDefs();
            this.showGrid = true;
        }
```

but I get the following error at run time, do you have any idea?
![error](https://user-images.githubusercontent.com/25340570/43392512-1effe2b8-9409-11e8-8330-1e25094e1d49.PNG)

**Comment by seanlandsman** [comment]
HI

This area has changed - the latest version will give you the following warning:

ag-grid: since version 19.x, gridAutoHeight is gone, please use domLayout=autoHeight instead

thanks
