### ISSUE TITLE
How to get single js file ag-grid + ag-grid-vue ?

### ISSUE THREAD

**Issue by Jung-Younghun** [ag-grid/ag-grid-vue#26]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
To use ag-grid-vue, ag-grid need to be installed from npm and loaded before.
ag-grid > ag-grid-vue

**Expected behavior**
However, In case of not using npm, How can I get single javascript file including ag-grid.js and ag-grid-vue? Is there any way?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-vue version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **VueJS version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
The next version of ag-grid-vue (to be released next month) will support this - take a look at https://github.com/seanlandsman/ag-grid-vue-umd when ag-grid-vue 20.x has been released

thanks
