### ISSUE TITLE
Vue JS warnings when following the 'getting started' example.

### ISSUE THREAD

**Issue by amanpatel** [ag-grid/ag-grid-vue#29]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Warnings in the console that show this:
[Vue warn]: $attrs is readonly.
[Vue warn]: $listeners is readonly.

**Expected behavior**
Warnings should not occur

**Minimal reproduction of the problem with instructions**
VUEJS 2.5.13 Loading the example as stated in "getting started with vue" example.

**What is the motivation / use case for changing the behavior?**
Warnings...

**Please tell us about your environment:**
--

* **ag-grid-vue version:** 2.0.X
I am using 19.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
no enterprise here, just community

* **VueJS version:** 2.0.X
I'm on 2.5.13

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 69

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mazur-m** [comment]
Same here, VueJS version: 3.1.1

**Comment by ryanlemon** [comment]
Meet the same warn msg

**Comment by seanlandsman** [comment]
@amanpatel @mazur-m @ryanlemon 

I've just tried walking through this and couldn't replicate it. Can you please check and confirm that this is still an issue?

If it is, at what step in the tutorial did you get the warning?

thanks

**Comment by leinue** [comment]
Meet the same warn msg
