### ISSUE TITLE
Missing definition file

### ISSUE THREAD

**Issue by frods** [ag-grid/ag-grid-vue#32]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After installing ```"ag-grid-vue": "^19.1.2"``` and importing it I am getting the type error:
```
  ERROR in /Users/vue_project/src/router/views/list/Available.vue
  3:27 Could not find a declaration file for module 'ag-grid-vue'. '/Users/philip/vue_project/node_modules/ag-grid-vue/main.js' implicitly has an 'any' type.
    Try `npm install @types/ag-grid-vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'ag-grid-vue';`
      1 | <script lang="ts">
      2 | import Vue from 'vue';
    > 3 | import { AgGridVue } from 'ag-grid-vue';
        |                           ^
      4 | import Layout from '@/router/layouts/main.vue';
      5 | import HeaderBar from './components/header-bar.vue';
      6 | import TitleBar from './components/title-bar.vue';
```

**Expected behavior**
No type errors.

**Minimal reproduction of the problem with instructions**
The code snippet in the error above will reproduce the problem.

**What is the motivation / use case for changing the behavior?**
Type errors should not be ignored or it will promote writing sloppy TypeScript.

**Please tell us about your environment:**
macOS 10.13.6
npm 6.1.0

* **ag-grid-vue version:** 2.0.X
19.1.2

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
18.1.2

* **VueJS version:** 2.0.X
2.5.17

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.2.1

**Comment by seanlandsman** [comment]
Hi

The next version of ag-grid-vue will have typings included. In the meantime you can create a globals.d.ts file and add the following to it:

```declare module "ag-grid-vue";```
