### ISSUE TITLE
as child component cannot normal display

### ISSUE THREAD

**Issue by leefreeF** [ag-grid/ag-grid-vue#33]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
 components cannot show In the absence of any operational behavior
is childComponent
!!![Vue warn]: $attrs is readonly!!!
!!![Vue warn]: $listeners is readonly!!!

**Expected behavior**
 components show

**Minimal reproduction of the problem with instructions**
```
<template lang="html">
            <ag-grid-vue
                class="ag-theme-balham"
                style="width: 500px; height: 500px;"
                :columnDefs="columnDefs"
                :rowData="rowData">
            </ag-grid-vue>
</template>
<script>
    import {AgGridVue} from "ag-grid-vue";
    export default {
        name: 'stepThree',
        data () {
            return {
                columnDefs: null,
                rowData: null
            };
        },
        beforeMount () {
            this.columnDefs = [
                {headerName: 'Make', field: 'make'},
                {headerName: 'Model', field: 'model'},
                {headerName: 'Price', field: 'price'}
            ];

            this.rowData = [
                {make: 'Toyota', model: 'Celica', price: 35000},
                {make: 'Ford', model: 'Mondeo', price: 32000},
                {make: 'Porsche', model: 'Boxter', price: 72000}
            ];
        }
        components: {
            AgGridVue
        }
    };
</script>
<style lang="css">
    @import "~ag-grid-community/dist/styles/ag-grid.css";
    @import "~ag-grid-community/dist/styles/ag-theme-balham.css";
</style>
```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
mac Os high Sierra（10.13.6）

* **ag-grid-vue version:** 2.0.X
"ag-grid-vue": "^19.1.2",

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
"ag-grid-community": "^19.1.4",

* **VueJS version:** 2.0.X
"vue": "^2.5.2",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi,

I've just tried this and I'm afraid I don't see any errors in the log. If you can provide a repro of this (preferably a github repo I can just checkout and run) I'd be happy to take a look at this again.

thanks
