### ISSUE TITLE
gridReady doesn't work

### ISSUE THREAD

**Issue by GregEremeev** [ag-grid/ag-grid-vue#34]
**I'm submitting a bug report**

**Current behavior**
grid doesn't invoke passed function

**Expected behavior**
grid invokes passed function

**Minimal reproduction of the problem with instructions**
(I followed this instruction - https://www.ag-grid.com/vue-getting-started/#enable-selection)
1. set up gridReady prop on a component:
```
<ag-grid-vue class="ag-theme-balham" :columnDefs="columnDefs" :rowData="tariffs" rowSelection="multiple" :gridReady="onGridReady"></ag-grid-vue>
```
2. set up method onGridReady:
```javascript
    methods: {
      onGridReady (params) {
        this.gridApi = params.api;
        this.columnApi = params.columnApi;
      },
```
**What is the motivation / use case for changing the behavior?**
Can't use gridReady callback on 20.0.0 version of ag-grid-vue

**Please tell us about your environment:**
MacOS 10.14.3, WebStorm, npm 6.5.0, vue-cli 3.3.0

* **ag-grid-vue version: 20.0.0** 

* **ag-Grid-Community version: 20.0.0**

* **vue-property-decorator: 7.3.0**

* **VueJS version: 2.5.22**

* **Browser: Version 71.0.3578.98 (Official Build) (64-bit)**

* **Language: ES6**

**Comment by GregEremeev** [comment]
:gridReady="onGridReady" doesn't work in ag-grid-vue 20.0.0 version
but :onGridReady="onGridReady" works

in 19.1.2 both props work well

**Comment by gavinhungry** [comment]
@GregEremeev,

You should use `@grid-ready='onGridReady'` (or `@gridReady='onGridReady'`) here.

See:
https://www.ag-grid.com/best-vuejs-data-grid/#configuring-ag-grid-in-vuejs

**Comment by seanlandsman** [comment]
@GregEremeev - as @gavinhungry this was a breaking change to make ag-grid-vue more idiomatic

thanks
