### ISSUE TITLE
Allow latest version of vue-property-decorator

### ISSUE THREAD

**Issue by NoahStahl** [ag-grid/ag-grid-vue#35]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When running npm install, the following warning appears:

npm WARN ag-grid-vue@20.2.0 requires a peer of vue-property-decorator@^7.2.0 but none is installed

The project has vue-property-decorator version 8.1.0 installed.

**Expected behavior**
Latest version of vue-property-decorator should satisfy the dependency without warning.

**Minimal reproduction of the problem with instructions**
Install a project using vue-property-decorator version 8 or above. Run npm install after referencing latest ag-grid-vue.

**What is the motivation / use case for changing the behavior?**
Reduce unneeded warnings.

**Please tell us about your environment:**

* **ag-grid-vue version:** 20.2.0

* **ag-Grid/ag-Grid-Enterprise version:** 20.2.0

* **VueJS version:** 2.6.10

**Comment by DanMiMe** [comment]
I have the same warning, with ag grid 21.2:

npm WARN ag-grid-vue@21.2.0 requires a peer of vue-property-decorator@^7.2.0 but none is installed. You must install peer dependencies yourself.

**Comment by seanlandsman** [comment]
Hi - 22.x should resolve this issue.

thanks
