### ISSUE TITLE
Cannot use tree data in component slot

### ISSUE THREAD

**Issue by Jennifer7788** [ag-grid/ag-grid-vue#37]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

``` html
<template>
    <div style="height: 100%;">
        <!-- it work --->
        <tree-view />

        <Usage
                :attributesDoc="attributesDoc"
        >
            <div slot="examples">
                <Panel title="Normal">
                    <!-- not work --->
                    <tree-view slot="component" />
                    <div slot="code" v-code.html>{{usage.base}}</div>
                </Panel>
            </div>
        </Usage>
    </div>
</template>
```

**Expected behavior**

should work in component slot

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-vue version:** 21.0.1

* **ag-Grid/ag-Grid-Enterprise version:** 21.0.1

* **VueJS version:** 2.6.7

* **Browser:** Chrome 75.0.3770.100

* **Language:** ES6/7

**Comment by seanlandsman** [comment]
As per the issue template please provide a repro of the issue
