### ISSUE TITLE
make ag-grid-vue globally

### ISSUE THREAD

**Issue by oedemis** [ag-grid/ag-grid-vue#38]
I want register AgGridVue as global, then I want use it in another vue app .
My Approach in app-grid-vue project in main.ts add this global publication
Vue.component('ag-grid-vue', AgGridVue);

then npm build

Afterward the compoent 'ag-grid-vue'' it is not dedected in my another vue app.
I bind the ag-grid-vue throught the compiled ag-grid-vue .umd.js

PS: The App that want use ag-grid-vue is client based and has not require, and import capabilities

**Comment by seanlandsman** [comment]
Hi,

I'm afraid I do not fully understand this issue - please feel free to raise an issue on https://github.com/ag-grid/ag-grid along with a working repro of your issue
