### ISSUE TITLE
Datepicker  not working when we set :stopEditingWhenGridLosesFocus=true

### ISSUE THREAD

**Issue by waseembarcha** [ag-grid/ag-grid-vue#39]
When we set stopEditingWhenGridLosesFocus to true, the datepicker, timepicker and dropdown menus won't work properly. It works fine with default HTML5 datepicker and time picker.
![Datetimepicker_issue](https://user-images.githubusercontent.com/37862628/66064094-290e4b80-e55e-11e9-8901-cf412f364a81.gif)

```

**Comment by seanlandsman** [comment]
As per the issue template please provide a repro of the issue
