### ISSUE TITLE
Slow setup time (linear to size of grid)

### ISSUE THREAD

**Issue by seanw** [ag-grid/ag-grid-vue#5]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ag-grid/ag-grid-vue/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using ag-grid Vue, initial setup of the grid can take over a second for collections with 10K items and it gets slower linearly with the size of the grid (e.g. 2 seconds for 20K items). See example here forked from the Vue example repo:
https://github.com/seanw/ag-grid-vue-example/commit/02c6e7ee101cf53d15fa3e5f14a6f941de233fb4

Start the app with webpack server, then click on "dynamic components example". For a 20K sized collection, it takes around 1 second on my machine for that component to get from "beforeMount" to "mounted" being called. For a 40K sized collection, it takes 2 seconds etc. Even for modest sized collection, this setup introduces significant lag to the UI.

I've attached a JavaScript profile taken when setting up the example grid once for 20K rows:

<img width="1149" alt="screen shot 2017-09-03 at 17 03 38" src="https://user-images.githubusercontent.com/2026117/30004631-ded8714c-90ca-11e7-9b48-395278d6c014.png">

The profile seems to indicate the vast majority of the time is spent in Vue methods related to reactivity (e.g. defineReactive, observeArray, dependArray). Not an expert here but I'm guessing Vue is setting up observers for all the array items each time which is slowing initial setup and anything to do with working with the arrays (e.g. you can see similar methods being triggered when sorting happens). I can't see this behaviour when using plain JavaScript ag-grid.

I tried doing Object.freeze on the whole array to stop Vue observing it but it didn't make an obvious difference. I found the same delay exists if even if you reuse the grid and swap the data out with api.setRowData. I'd be happy for now disabling reactive features completely on the grid data as a temporary fix as I don't need to incrementally update it ever but I want to be able to use Vue components as cell renderers.

**Expected behavior**

The grid should set up in a reasonable time that does not grow linearly with the grid size.

**Minimal reproduction of the problem with instructions**

See https://github.com/seanw/ag-grid-vue-example/commit/02c6e7ee101cf53d15fa3e5f14a6f941de233fb4
 and above.

**What is the motivation / use case for changing the behavior?**

My actual use case is similar to the example where you can use tabs to switch between several grid views where each can contain large arrays. 

**Please tell us about your environment:**

MacOS Sierra. Node 7.10.

* **ag-grid-vue version:** 

ag-grid 13.0

* **ag-Grid/ag-Grid-Enterprise version:** 

N/A

* **VueJS version:** 2.0.X

ag-grid-vue 13.0

* **Browser:** 

Chrome 60

* **Language:** 

all

**Comment by seanlandsman** [comment]
Hi - I can confirm that your patch fixes this - thanks again

**Comment by seanlandsman** [comment]
There was an issue around this that has now been fixed.

When creating data I'd suggest you create it "outside" of vue, or Object.freeze it if you can.  If you dont then Vue will watch it (probably unnecessarily) and create a larger footprint that necessary. It will also slow your app down.

There is a a large data example on the latest branch here (https://github.com/ag-grid/ag-grid-vue-example/tree/latest/src/large-data-set-example) that creates 50k of rows just fine, with a small memory footprint (with the recent fix I allude to above)

Please wait for our next release (end of next week) and retry - it should be better 

thanks
